version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/appFlask
    command: python app.py
    environment:
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/users
    depends_on:
      - mongo
  mongo:
    image: mongo
